
[font]
size = 15.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
# space between the text and the window border
padding = { x = 12, y = 12 }

# optional: let Alacritty adjust padding when resizing
dynamic_padding = true

[general]
import = ["~/.cache/wal/colors-alacritty.toml"]
