--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Akshat/Downloads/Clearnight.jpg"

-- Special
background="#0b0c1b"
foreground="#c2c2c6"
cursor="#c2c2c6"

-- Colors
color0="#0b0c1b"
color1="#08368B"
color2="#102F99"
color3="#1255A5"
color4="#4B4999"
color5="#106ED0"
color6="#1697E1"
color7="#c2c2c6"
color8="#5a5c6f"
color9="#08368B"
color10="#102F99"
color11="#1255A5"
color12="#4B4999"
color13="#106ED0"
color14="#1697E1"
color15="#c2c2c6"
