# Shell variables
# Generated by 'wal'
wallpaper="/home/Akshat/Downloads/Clearnight.jpg"

# Special
background='#0b0c1b'
foreground='#c2c2c6'
cursor='#c2c2c6'

# Colors
color0='#0b0c1b'
color1='#08368B'
color2='#102F99'
color3='#1255A5'
color4='#4B4999'
color5='#106ED0'
color6='#1697E1'
color7='#c2c2c6'
color8='#5a5c6f'
color9='#08368B'
color10='#102F99'
color11='#1255A5'
color12='#4B4999'
color13='#106ED0'
color14='#1697E1'
color15='#c2c2c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
