[colors]
background = '#0b0c1b8e'
black = '#0b0c1b'
blue = '#08368B'
cursor = '#c2c2c6'
cyan = '#102F99'
foreground = '#c2c2c6'
green = '#1255A5'
magenta = '#4B4999'
red = '#106ED0'
tabs = '#c2c2c6'
tabs-active = '#1697E1'
white = '#c2c2c6'
yellow = '#c2c2c6'
dim-black = '#0b0c1b8e'
dim-blue = '#08368B8e'
dim-cyan = '#102F998e'
dim-foreground = '#c2c2c68e'
dim-green = '#1255A58e'
dim-magenta = '#4B49998e'
dim-red = '#106ED08e'
dim-white = '#1697E18e'
dim-yellow = '#c2c2c68e'
light-black = '#08368B'
light-blue = '#102F99'
light-cyan = '#1255A5'
light-foreground = '#4B4999'
light-green = '#106ED0'
light-magenta = '#1697E1'
light-red = '#c2c2c6'
light-white = '#08368B'
light-yellow = '#102F99'
